openapi: 3.0.0
info:
  description: >-
    This is the API spec for the integration between EDH and CVS for synchronising Activity records.
  version: 1.0.0
  title: Activity CVS->EDH integration
  termsOfService: ''
  contact:
    email: akothiyal@deloitte.co.uk
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /activities/{id}:
    post:
      summary: Create a new activity.
      requestBody:
        description: POST the new activity.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/activity'
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Activity ID
      responses:
        '202':
          description: Accepted
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Operation Not Supported
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
    put:
      summary: Update an activity.
      requestBody:
        description: PUT the changed activity.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/activity'
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Activity ID
      responses:
        '202':
          description: Accepted
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Operation Not Supported
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
    delete:
      summary: Delete the identified activity - will probably never be used.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Activity ID
      responses:
        '202':
          description: Accepted
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Operation Not Supported
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://example.com/oauth/authorize'
          tokenUrl: 'https://example.com/oauth/token'
          scopes:
            read: Grants read access
            write: Grants write access
  schemas:
    activity:
      type: object
      additionalProperties: false
      properties:
        id:
          type: number
        parentId:
          type: string
          nullable: true
        activityType:
          type: string
          enum:
            - visit
            - wait
            - unaccountable time
        startTime:
          type: string
          format: date-time
        activityDay:
          type: string
          format: date
          nullable: true
        endTime:
          type: string
          format: date-time
          nullable: true
        testStationName:
          type: string
        testStationPNumber:
          type: string
        testStationEmail:
          type: string
        testStationType:
          type: string
          enum:
            - atf
            - gvts
            - hq
        testerName:
          type: string
        testerStaffId:
          type: string
        testerEmail:
          type: string
          format: email
          description: Required if the activity type is "visit"
        waitReason:
          type: array
          items:
            type: string
          nullable: true
        notes:
          type: string
          nullable: true
security:
  - OAuth2:
      - read
      - write
servers:
  - url: 'https://url/api/v1'
